// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package statspg

import (
	"context"
)

const getCoreOverview = `-- name: GetCoreOverview :one
SELECT
  (SELECT COUNT(*) FROM lps_players)::bigint AS total_players,
  (SELECT COUNT(DISTINCT steam_id)
     FROM lps_sessions
    WHERE lps_sessions.last_saved_at >= $1
      AND lps_sessions.active_play_seconds > 0)::bigint AS active_players_7d,
  (SELECT COALESCE(SUM(active_play_seconds), 0) FROM lps_sessions)::bigint AS total_active_play_seconds,
  (SELECT COUNT(*) FROM lps_runs
    WHERE mode_family = 'pve' AND game_mode IN ('coop', 'realism') AND status = 'completed')::bigint AS completed_pve_runs,
  (SELECT COUNT(*) FROM lps_runs
    WHERE mode_family = 'versus' AND game_mode = 'versus' AND status = 'completed')::bigint AS completed_versus_runs
`

type GetCoreOverviewRow struct {
	TotalPlayers           int64
	ActivePlayers7d        int64
	TotalActivePlaySeconds int64
	CompletedPveRuns       int64
	CompletedVersusRuns    int64
}

func (q *Queries) GetCoreOverview(ctx context.Context, lastSavedAt int64) (GetCoreOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, getCoreOverview, lastSavedAt)
	var i GetCoreOverviewRow
	err := row.Scan(
		&i.TotalPlayers,
		&i.ActivePlayers7d,
		&i.TotalActivePlaySeconds,
		&i.CompletedPveRuns,
		&i.CompletedVersusRuns,
	)
	return i, err
}

const getPVEOverview = `-- name: GetPVEOverview :one
SELECT
  COALESCE(SUM(p.common_kills), 0)::bigint AS common_kills,
  COALESCE(SUM(p.special_kills), 0)::bigint AS special_kills,
  COALESCE(SUM(p.tank_kills), 0)::bigint AS tank_kills,
  COALESCE(SUM(p.witch_kills), 0)::bigint AS witch_kills,
  COALESCE(SUM(p.incap_revives + p.ledge_rescues + p.defib_revives), 0)::bigint AS rescues
FROM lps_pve_segment_stats p
JOIN lps_player_segments s ON s.segment_id = p.segment_id
JOIN lps_runs r ON r.run_id = s.run_id
WHERE p.stats_version = 1
  AND r.mode_family = 'pve'
  AND r.game_mode IN ('coop', 'realism')
`

type GetPVEOverviewRow struct {
	CommonKills  int64
	SpecialKills int64
	TankKills    int64
	WitchKills   int64
	Rescues      int64
}

func (q *Queries) GetPVEOverview(ctx context.Context) (GetPVEOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, getPVEOverview)
	var i GetPVEOverviewRow
	err := row.Scan(
		&i.CommonKills,
		&i.SpecialKills,
		&i.TankKills,
		&i.WitchKills,
		&i.Rescues,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT COALESCE(MAX(version), 0)::bigint AS version FROM lps_schema_migrations
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getServerRecent24h = `-- name: GetServerRecent24h :one
SELECT
  (SELECT COUNT(DISTINCT steam_id)::bigint
     FROM lps_sessions
    WHERE lps_sessions.server_key = $1
      AND lps_sessions.last_saved_at >= $2
      AND lps_sessions.active_play_seconds > 0) AS active_players,
  (SELECT COALESCE(SUM(p.common_kills), 0)::bigint
     FROM lps_pve_segment_stats p
     JOIN lps_player_segments s ON s.segment_id = p.segment_id
     JOIN lps_runs r ON r.run_id = s.run_id
    WHERE s.server_key = $1
      AND p.last_saved_at >= $2
      AND p.stats_version = 1
      AND r.mode_family = 'pve'
      AND r.game_mode IN ('coop', 'realism')) AS common_kills,
  (SELECT COALESCE(SUM(p.special_kills), 0)::bigint
     FROM lps_pve_segment_stats p
     JOIN lps_player_segments s ON s.segment_id = p.segment_id
     JOIN lps_runs r ON r.run_id = s.run_id
    WHERE s.server_key = $1
      AND p.last_saved_at >= $2
      AND p.stats_version = 1
      AND r.mode_family = 'pve'
      AND r.game_mode IN ('coop', 'realism')) AS special_kills,
  (SELECT COUNT(*)::bigint
     FROM lps_runs
    WHERE lps_runs.server_key = $1
      AND lps_runs.mode_family = 'pve'
      AND lps_runs.game_mode IN ('coop', 'realism')
      AND lps_runs.status = 'completed'
      AND COALESCE(lps_runs.ended_at, lps_runs.last_saved_at) >= $2) AS completed_runs
`

type GetServerRecent24hParams struct {
	FilterServerKey string
	CutoffAt        int64
}

type GetServerRecent24hRow struct {
	ActivePlayers int64
	CommonKills   int64
	SpecialKills  int64
	CompletedRuns int64
}

func (q *Queries) GetServerRecent24h(ctx context.Context, arg GetServerRecent24hParams) (GetServerRecent24hRow, error) {
	row := q.db.QueryRowContext(ctx, getServerRecent24h, arg.FilterServerKey, arg.CutoffAt)
	var i GetServerRecent24hRow
	err := row.Scan(
		&i.ActivePlayers,
		&i.CommonKills,
		&i.SpecialKills,
		&i.CompletedRuns,
	)
	return i, err
}

const getVersusOverview = `-- name: GetVersusOverview :one
SELECT
  (SELECT COUNT(*)
     FROM lps_versus_run_results vr
     JOIN lps_runs r ON r.run_id = vr.run_id
    WHERE vr.stats_version = 1 AND vr.result_status = 'completed'
      AND r.mode_family = 'versus' AND r.game_mode = 'versus')::bigint AS completed_matches,
  (SELECT COUNT(*)
     FROM lps_versus_round_results rr
     JOIN lps_rounds r ON r.round_id = rr.round_id
    WHERE rr.stats_version = 1 AND rr.result_status = 'completed'
      AND r.mode_family = 'versus')::bigint AS completed_halves,
  (SELECT COALESCE(SUM(v.human_special_kills + v.human_tank_kills), 0)
     FROM lps_versus_survivor_stats v
     JOIN lps_player_segments s ON s.segment_id = v.segment_id
     JOIN lps_runs r ON r.run_id = s.run_id
    WHERE v.stats_version = 1 AND s.side = 'survivor'
      AND r.mode_family = 'versus' AND r.game_mode = 'versus')::bigint AS human_controlled_infected_kills,
  (SELECT COALESCE(SUM(c.human_survivor_controls), 0)
     FROM lps_versus_infected_class_stats c
     JOIN lps_player_segments s ON s.segment_id = c.segment_id
     JOIN lps_runs r ON r.run_id = s.run_id
    WHERE c.stats_version = 1 AND s.side = 'infected'
      AND r.mode_family = 'versus' AND r.game_mode = 'versus')::bigint AS human_survivor_controls
`

type GetVersusOverviewRow struct {
	CompletedMatches             int64
	CompletedHalves              int64
	HumanControlledInfectedKills int64
	HumanSurvivorControls        int64
}

func (q *Queries) GetVersusOverview(ctx context.Context) (GetVersusOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, getVersusOverview)
	var i GetVersusOverviewRow
	err := row.Scan(
		&i.CompletedMatches,
		&i.CompletedHalves,
		&i.HumanControlledInfectedKills,
		&i.HumanSurvivorControls,
	)
	return i, err
}
