// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package statssqlite

type LpsIncident struct {
	RoundID            string
	IncidentSeq        int64
	IncidentVersion    int64
	IncidentType       int64
	OccurredAt         int64
	RoundOffsetMs      int64
	DurationMs         int64
	ActorKind          int64
	ActorSteamID       string
	TargetKind         int64
	TargetSteamID      string
	HelperKind         int64
	HelperSteamID      string
	InfectedClass      int64
	EndReason          int64
	DetailFlags        int64
	RelatedIncidentSeq int64
	PosX               interface{}
	PosY               interface{}
	PosZ               interface{}
	EndPosX            interface{}
	EndPosY            interface{}
	EndPosZ            interface{}
}

type LpsPlayer struct {
	SteamID     string
	LastName    string
	FirstSeenAt int64
	LastSeenAt  int64
}

type LpsPlayerSegment struct {
	SegmentID         string
	SessionID         string
	RunID             string
	RoundID           string
	ServerKey         string
	SteamID           string
	Side              string
	StartedAt         int64
	EndedAt           interface{}
	LastSavedAt       int64
	ActivePlaySeconds int64
	Status            string
	Revision          int64
}

type LpsPveSegmentEquipmentStat struct {
	SegmentID       string
	EquipmentID     int64
	StatsVersion    int64
	LastSavedAt     int64
	Actions         int64
	CommonKills     int64
	SpecialKills    int64
	TankKills       int64
	WitchKills      int64
	HeadshotKills   int64
	DamageToSpecial int64
	DamageToTank    int64
	DamageToWitch   int64
	Revision        int64
}

type LpsPveSegmentStat struct {
	SegmentID                   string
	StatsVersion                int64
	LastSavedAt                 int64
	CommonKills                 int64
	SpecialKills                int64
	TankKills                   int64
	WitchKills                  int64
	DamageToSpecial             int64
	DamageToTank                int64
	DamageToWitch               int64
	DamageTakenInfected         int64
	FriendlyFireToHumans        int64
	FriendlyFireToBots          int64
	FriendlyFireTaken           int64
	Incapacitations             int64
	Deaths                      int64
	IncapRevives                int64
	LedgeRescues                int64
	DefibRevives                int64
	RescuesReceived             int64
	MedkitsUsedSelf             int64
	MedkitsUsedOnOthers         int64
	MedkitHealingSelf           int64
	MedkitHealingOthers         int64
	PillsUsed                   int64
	AdrenalineUsed              int64
	TemporaryHealthReceived     int64
	ChapterParticipations       int64
	ChapterCompletionsAlive     int64
	ChapterCompletionsDead      int64
	CampaignCompletions         int64
	SmokerKills                 int64
	BoomerKills                 int64
	HunterKills                 int64
	SpitterKills                int64
	JockeyKills                 int64
	ChargerKills                int64
	DamageToSmoker              int64
	DamageToBoomer              int64
	DamageToHunter              int64
	DamageToSpitter             int64
	DamageToJockey              int64
	DamageToCharger             int64
	SmokerControlsReceived      int64
	HunterControlsReceived      int64
	JockeyControlsReceived      int64
	ChargerControlsReceived     int64
	SmokerControlledSeconds     int64
	HunterControlledSeconds     int64
	JockeyControlledSeconds     int64
	ChargerControlledSeconds    int64
	SmokerSaves                 int64
	HunterSaves                 int64
	JockeySaves                 int64
	ChargerSaves                int64
	MeleeTongueSelfCuts         int64
	TankRocksDestroyed          int64
	WitchOneshots               int64
	WitchSoloKills              int64
	TankEncounters              int64
	TankKillParticipations      int64
	WitchEncounters             int64
	WitchKillParticipations     int64
	IncendiaryPacksDeployed     int64
	ExplosivePacksDeployed      int64
	ObjectiveInteractions       int64
	AmmoPileUses                int64
	IncapacitatedSeconds        int64
	LedgeHangingSeconds         int64
	BlackWhiteTeammatesRestored int64
	Revision                    int64
	CarAlarmsTriggered          interface{}
}

type LpsRound struct {
	RoundID     string
	RunID       string
	ServerKey   string
	ModeFamily  string
	MapName     string
	RoundSeq    int64
	MapSeq      int64
	AttemptNo   int64
	HalfNo      int64
	StartedAt   int64
	EndedAt     interface{}
	LastSavedAt int64
	Status      string
	Revision    int64
}

type LpsRoundContext struct {
	RoundID                 string
	ContextVersion          int64
	CapturedAt              int64
	LastSavedAt             int64
	CollectorVersion        string
	RulesetName             string
	Difficulty              string
	SurvivorLimit           int64
	MaxPlayerZombies        int64
	CommonLimit             int64
	TankHealth              int64
	WitchHealth             int64
	ChangeMask              int64
	IncidentCaptureEnabled  int64
	IncidentCaptureComplete int64
	IncidentExpectedCount   int64
	IncidentDroppedCount    int64
	Revision                int64
}

type LpsRun struct {
	RunID               string
	BootID              string
	ServerKey           string
	ModeFamily          string
	GameMode            string
	CampaignKey         string
	StartedAt           int64
	EndedAt             interface{}
	LastSavedAt         int64
	Status              string
	RoundCount          int64
	CompletedRoundCount int64
	FailedRoundCount    int64
	Revision            int64
}

type LpsSchemaMigration struct {
	Version   int64
	Name      string
	AppliedAt int64
}

type LpsServer struct {
	ServerKey   string
	DisplayName string
	FirstSeenAt int64
	LastSeenAt  int64
}

type LpsServerBoot struct {
	BootID          string
	ServerKey       string
	StartedAt       int64
	EndedAt         interface{}
	LastHeartbeatAt int64
	Status          string
}

type LpsSession struct {
	SessionID         string
	BootID            string
	ServerKey         string
	SteamID           string
	PlayerName        string
	IpAddress         string
	StartedAt         int64
	EndedAt           interface{}
	LastSavedAt       int64
	ConnectedSeconds  int64
	ActivePlaySeconds int64
	Status            string
	DisconnectReason  string
	Revision          int64
}

type LpsVersusInfectedClassStat struct {
	SegmentID                   string
	InfectedClass               int64
	StatsVersion                int64
	LastSavedAt                 int64
	SpawnCount                  int64
	DamageToHumanSurvivors      int64
	DamageToBotSurvivors        int64
	HumanSurvivorIncaps         int64
	BotSurvivorIncaps           int64
	HumanSurvivorKills          int64
	BotSurvivorKills            int64
	HumanSurvivorControls       int64
	BotSurvivorControls         int64
	HumanSurvivorControlSeconds int64
	BotSurvivorControlSeconds   int64
	HumanSurvivorAbilityHits    int64
	BotSurvivorAbilityHits      int64
	HumanSurvivorAbilityDamage  int64
	BotSurvivorAbilityDamage    int64
	Revision                    int64
}

type LpsVersusInfectedStat struct {
	SegmentID              string
	StatsVersion           int64
	LastSavedAt            int64
	SpawnCount             int64
	DamageToHumanSurvivors int64
	DamageToBotSurvivors   int64
	HumanSurvivorIncaps    int64
	BotSurvivorIncaps      int64
	HumanSurvivorKills     int64
	BotSurvivorKills       int64
	Revision               int64
}

type LpsVersusRoundResult struct {
	RoundID            string
	StatsVersion       int64
	LastSavedAt        int64
	ScoringTeamSlot    int64
	TeamsFlipped       int64
	Team0MapScore      int64
	Team1MapScore      int64
	Team0CampaignScore int64
	Team1CampaignScore int64
	RawWinnerTeam      int64
	ScoreAvailable     int64
	ResultStatus       string
	FinalizedAt        int64
	Revision           int64
}

type LpsVersusRunResult struct {
	RunID              string
	StatsVersion       int64
	LastSavedAt        int64
	Team0CampaignScore int64
	Team1CampaignScore int64
	WinnerTeamSlot     int64
	RawWinnerTeam      int64
	ScoreAvailable     int64
	ResultStatus       string
	FinalizedAt        interface{}
	Revision           int64
}

type LpsVersusSurvivorInfectedClassStat struct {
	SegmentID                string
	InfectedClass            int64
	StatsVersion             int64
	LastSavedAt              int64
	HumanControllerKills     int64
	BotControllerKills       int64
	DamageToHumanControllers int64
	DamageToBotControllers   int64
	Revision                 int64
}

type LpsVersusSurvivorStat struct {
	SegmentID               string
	StatsVersion            int64
	LastSavedAt             int64
	CommonKills             int64
	HumanSpecialKills       int64
	BotSpecialKills         int64
	HumanTankKills          int64
	BotTankKills            int64
	DamageToHumanSpecial    int64
	DamageToBotSpecial      int64
	DamageToHumanTank       int64
	DamageToBotTank         int64
	DamageTakenInfected     int64
	FriendlyFireToHumans    int64
	FriendlyFireToBots      int64
	FriendlyFireTaken       int64
	Incapacitations         int64
	Deaths                  int64
	IncapRevives            int64
	LedgeRescues            int64
	DefibRevives            int64
	RescuesReceived         int64
	MedkitsUsedSelf         int64
	MedkitsUsedOnOthers     int64
	MedkitHealingSelf       int64
	MedkitHealingOthers     int64
	PillsUsed               int64
	AdrenalineUsed          int64
	TemporaryHealthReceived int64
	WitchKills              int64
	DamageToWitch           int64
	MolotovsThrown          int64
	PipeBombsThrown         int64
	VomitJarsThrown         int64
	IncendiaryPacksDeployed int64
	ExplosivePacksDeployed  int64
	MeleeTongueSelfCuts     int64
	TankRocksDestroyed      int64
	WitchOneshots           int64
	WitchSoloKills          int64
	Revision                int64
	CarAlarmsTriggered      interface{}
	ObjectiveInteractions   interface{}
}
