// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package statssqlite

import (
	"context"
)

type Querier interface {
	GetCoreOverview(ctx context.Context, lastSavedAt int64) (GetCoreOverviewRow, error)
	GetPVEOverview(ctx context.Context) (GetPVEOverviewRow, error)
	GetPlayerPVE(ctx context.Context, arg GetPlayerPVEParams) (GetPlayerPVERow, error)
	GetPlayerSummary(ctx context.Context, steamID string) (GetPlayerSummaryRow, error)
	GetPlayerVersus(ctx context.Context, arg GetPlayerVersusParams) (GetPlayerVersusRow, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	GetServerRecent24h(ctx context.Context, arg GetServerRecent24hParams) (GetServerRecent24hRow, error)
	GetVersusOverview(ctx context.Context) (GetVersusOverviewRow, error)
	ListActivePlayersByServer(ctx context.Context, arg ListActivePlayersByServerParams) ([]ListActivePlayersByServerRow, error)
	ListPlayerChapters(ctx context.Context, arg ListPlayerChaptersParams) ([]ListPlayerChaptersRow, error)
	ListPlayerSessions(ctx context.Context, arg ListPlayerSessionsParams) ([]ListPlayerSessionsRow, error)
	SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error)
}

var _ Querier = (*Queries)(nil)
