// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dashsql

import (
	"context"
)

const completeAggregateBuild = `-- name: CompleteAggregateBuild :exec
UPDATE aggregate_state SET state = 'ready', last_finished_at = ?1,
  source_rows = ?2, aggregate_rows = ?3, source_watermark = ?4,
  last_duration_ms = ?5, last_changed_days = ?6, last_build_mode = ?7,
  aggregate_version = ?8, last_error = '' WHERE id = 1
`

type CompleteAggregateBuildParams struct {
	LastFinishedAt   int64  `json:"last_finished_at"`
	SourceRows       int64  `json:"source_rows"`
	AggregateRows    int64  `json:"aggregate_rows"`
	SourceWatermark  int64  `json:"source_watermark"`
	LastDurationMs   int64  `json:"last_duration_ms"`
	LastChangedDays  int64  `json:"last_changed_days"`
	LastBuildMode    string `json:"last_build_mode"`
	AggregateVersion int64  `json:"aggregate_version"`
}

func (q *Queries) CompleteAggregateBuild(ctx context.Context, arg CompleteAggregateBuildParams) error {
	_, err := q.db.ExecContext(ctx, completeAggregateBuild,
		arg.LastFinishedAt,
		arg.SourceRows,
		arg.AggregateRows,
		arg.SourceWatermark,
		arg.LastDurationMs,
		arg.LastChangedDays,
		arg.LastBuildMode,
		arg.AggregateVersion,
	)
	return err
}

const countAdminAccounts = `-- name: CountAdminAccounts :one
SELECT COUNT(*) FROM admin_account
`

func (q *Queries) CountAdminAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAggregateRows = `-- name: CountAggregateRows :one
SELECT
  (SELECT COUNT(*) FROM aggregate_rows) +
  (SELECT COUNT(*) FROM aggregate_monthly_rows) +
  (SELECT COUNT(*) FROM aggregate_lifetime_rows)
`

func (q *Queries) CountAggregateRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAggregateRows)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAnnouncements = `-- name: CountAnnouncements :one
SELECT COUNT(*) FROM announcements
WHERE (?1 = '' OR instr(lower(title), lower(?1)) > 0)
  AND (?2 = 0 OR CAST(strftime('%Y', updated_at, 'unixepoch') AS INTEGER) = ?2)
`

type CountAnnouncementsParams struct {
	TitleFilter interface{} `json:"title_filter"`
	YearFilter  interface{} `json:"year_filter"`
}

func (q *Queries) CountAnnouncements(ctx context.Context, arg CountAnnouncementsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnnouncements, arg.TitleFilter, arg.YearFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGameServers = `-- name: CountGameServers :one
SELECT COUNT(*) FROM game_servers
`

func (q *Queries) CountGameServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGameServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRetentionRuns = `-- name: CountRetentionRuns :one
SELECT COUNT(*) FROM retention_runs
`

func (q *Queries) CountRetentionRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRetentionRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteSettings = `-- name: CountSiteSettings :one
SELECT COUNT(*) FROM site_settings
`

func (q *Queries) CountSiteSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSiteSettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAccount = `-- name: CreateAdminAccount :exec
INSERT INTO admin_account (
  id, username, password_hash, jwt_secret, token_version,
  created_at, updated_at, password_changed_at
) VALUES (1, ?1, ?2, ?3, 1, ?4, ?4, ?4)
`

type CreateAdminAccountParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	JwtSecret    string `json:"jwt_secret"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAdminAccount,
		arg.Username,
		arg.PasswordHash,
		arg.JwtSecret,
		arg.CreatedAt,
	)
	return err
}

const createAnnouncement = `-- name: CreateAnnouncement :exec
INSERT INTO announcements (
  id, title, content_markdown, created_at, updated_at
) VALUES (?1, ?2, ?3, ?4, ?4)
`

type CreateAnnouncementParams struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	ContentMarkdown string `json:"content_markdown"`
	CreatedAt       int64  `json:"created_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) error {
	_, err := q.db.ExecContext(ctx, createAnnouncement,
		arg.ID,
		arg.Title,
		arg.ContentMarkdown,
		arg.CreatedAt,
	)
	return err
}

const createFooterLink = `-- name: CreateFooterLink :exec
INSERT INTO footer_links (
  id, label, url, sort_order, created_at, updated_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateFooterLinkParams struct {
	ID        string `json:"id"`
	Label     string `json:"label"`
	Url       string `json:"url"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateFooterLink(ctx context.Context, arg CreateFooterLinkParams) error {
	_, err := q.db.ExecContext(ctx, createFooterLink,
		arg.ID,
		arg.Label,
		arg.Url,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createGameServer = `-- name: CreateGameServer :exec
INSERT INTO game_servers (
  id, display_name, address, enabled, sort_order, created_at, updated_at
) VALUES (?1, ?2, ?3, 1, ?4, ?5, ?5)
`

type CreateGameServerParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Address     string `json:"address"`
	SortOrder   int64  `json:"sort_order"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateGameServer(ctx context.Context, arg CreateGameServerParams) error {
	_, err := q.db.ExecContext(ctx, createGameServer,
		arg.ID,
		arg.DisplayName,
		arg.Address,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const createRetentionRun = `-- name: CreateRetentionRun :exec
INSERT INTO retention_runs (
  id, executed_at, source_watermark, detail_cutoff, session_cutoff, result_cutoff,
  equipment_rows, versus_class_rows, session_rows,
  versus_round_result_rows, versus_run_result_rows, aggregate_version
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type CreateRetentionRunParams struct {
	ID                    string `json:"id"`
	ExecutedAt            int64  `json:"executed_at"`
	SourceWatermark       int64  `json:"source_watermark"`
	DetailCutoff          int64  `json:"detail_cutoff"`
	SessionCutoff         int64  `json:"session_cutoff"`
	ResultCutoff          int64  `json:"result_cutoff"`
	EquipmentRows         int64  `json:"equipment_rows"`
	VersusClassRows       int64  `json:"versus_class_rows"`
	SessionRows           int64  `json:"session_rows"`
	VersusRoundResultRows int64  `json:"versus_round_result_rows"`
	VersusRunResultRows   int64  `json:"versus_run_result_rows"`
	AggregateVersion      int64  `json:"aggregate_version"`
}

func (q *Queries) CreateRetentionRun(ctx context.Context, arg CreateRetentionRunParams) error {
	_, err := q.db.ExecContext(ctx, createRetentionRun,
		arg.ID,
		arg.ExecutedAt,
		arg.SourceWatermark,
		arg.DetailCutoff,
		arg.SessionCutoff,
		arg.ResultCutoff,
		arg.EquipmentRows,
		arg.VersusClassRows,
		arg.SessionRows,
		arg.VersusRoundResultRows,
		arg.VersusRunResultRows,
		arg.AggregateVersion,
	)
	return err
}

const deleteAggregateRows = `-- name: DeleteAggregateRows :exec
DELETE FROM aggregate_rows
`

func (q *Queries) DeleteAggregateRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAggregateRows)
	return err
}

const deleteAggregateRowsForDay = `-- name: DeleteAggregateRowsForDay :exec
DELETE FROM aggregate_rows WHERE day = ?1
`

func (q *Queries) DeleteAggregateRowsForDay(ctx context.Context, day int64) error {
	_, err := q.db.ExecContext(ctx, deleteAggregateRowsForDay, day)
	return err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements WHERE id = ?1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFooterLinks = `-- name: DeleteFooterLinks :exec
DELETE FROM footer_links
`

func (q *Queries) DeleteFooterLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFooterLinks)
	return err
}

const deleteGameServer = `-- name: DeleteGameServer :execrows
DELETE FROM game_servers WHERE id = ?1
`

func (q *Queries) DeleteGameServer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGameServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGameServers = `-- name: DeleteGameServers :exec
DELETE FROM game_servers
`

func (q *Queries) DeleteGameServers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGameServers)
	return err
}

const getAdminAccount = `-- name: GetAdminAccount :one
SELECT
  username, password_hash, jwt_secret, token_version,
  created_at, updated_at, password_changed_at
FROM admin_account
WHERE id = 1
`

type GetAdminAccountRow struct {
	Username          string `json:"username"`
	PasswordHash      string `json:"password_hash"`
	JwtSecret         string `json:"jwt_secret"`
	TokenVersion      int64  `json:"token_version"`
	CreatedAt         int64  `json:"created_at"`
	UpdatedAt         int64  `json:"updated_at"`
	PasswordChangedAt int64  `json:"password_changed_at"`
}

func (q *Queries) GetAdminAccount(ctx context.Context) (GetAdminAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminAccount)
	var i GetAdminAccountRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.JwtSecret,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getAggregateStatus = `-- name: GetAggregateStatus :one
SELECT state, last_started_at, last_finished_at, source_rows, aggregate_rows, last_error,
       source_watermark, last_duration_ms, last_changed_days, last_build_mode, aggregate_version
FROM aggregate_state WHERE id = 1
`

type GetAggregateStatusRow struct {
	State            string `json:"state"`
	LastStartedAt    int64  `json:"last_started_at"`
	LastFinishedAt   int64  `json:"last_finished_at"`
	SourceRows       int64  `json:"source_rows"`
	AggregateRows    int64  `json:"aggregate_rows"`
	LastError        string `json:"last_error"`
	SourceWatermark  int64  `json:"source_watermark"`
	LastDurationMs   int64  `json:"last_duration_ms"`
	LastChangedDays  int64  `json:"last_changed_days"`
	LastBuildMode    string `json:"last_build_mode"`
	AggregateVersion int64  `json:"aggregate_version"`
}

func (q *Queries) GetAggregateStatus(ctx context.Context) (GetAggregateStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getAggregateStatus)
	var i GetAggregateStatusRow
	err := row.Scan(
		&i.State,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.SourceRows,
		&i.AggregateRows,
		&i.LastError,
		&i.SourceWatermark,
		&i.LastDurationMs,
		&i.LastChangedDays,
		&i.LastBuildMode,
		&i.AggregateVersion,
	)
	return i, err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, title, content_markdown, created_at, updated_at
FROM announcements
WHERE id = ?1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id string) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataMaintenanceSettings = `-- name: GetDataMaintenanceSettings :one
SELECT aggregate_interval_minutes, detail_retention_days,
       session_retention_days, result_retention_days, updated_at
FROM data_maintenance_settings WHERE id = 1
`

type GetDataMaintenanceSettingsRow struct {
	AggregateIntervalMinutes int64 `json:"aggregate_interval_minutes"`
	DetailRetentionDays      int64 `json:"detail_retention_days"`
	SessionRetentionDays     int64 `json:"session_retention_days"`
	ResultRetentionDays      int64 `json:"result_retention_days"`
	UpdatedAt                int64 `json:"updated_at"`
}

func (q *Queries) GetDataMaintenanceSettings(ctx context.Context) (GetDataMaintenanceSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getDataMaintenanceSettings)
	var i GetDataMaintenanceSettingsRow
	err := row.Scan(
		&i.AggregateIntervalMinutes,
		&i.DetailRetentionDays,
		&i.SessionRetentionDays,
		&i.ResultRetentionDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameServer = `-- name: GetGameServer :one
SELECT
  id, display_name, address, enabled, sort_order
FROM game_servers
WHERE id = ?1
`

type GetGameServerRow struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Address     string `json:"address"`
	Enabled     int64  `json:"enabled"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) GetGameServer(ctx context.Context, id string) (GetGameServerRow, error) {
	row := q.db.QueryRowContext(ctx, getGameServer, id)
	var i GetGameServerRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Address,
		&i.Enabled,
		&i.SortOrder,
	)
	return i, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM dashboard_metadata WHERE key = ?1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getPublicSiteDocument = `-- name: GetPublicSiteDocument :one
SELECT key, enabled, content_markdown, updated_at
FROM site_documents
WHERE key = ?1 AND enabled = 1 AND content_markdown <> ''
`

func (q *Queries) GetPublicSiteDocument(ctx context.Context, key string) (SiteDocument, error) {
	row := q.db.QueryRowContext(ctx, getPublicSiteDocument, key)
	var i SiteDocument
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.ContentMarkdown,
		&i.UpdatedAt,
	)
	return i, err
}

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT enabled, description, image_url, updated_at
FROM site_seo_settings
WHERE id = 1
`

type GetSEOSettingsRow struct {
	Enabled     int64  `json:"enabled"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) GetSEOSettings(ctx context.Context) (GetSEOSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSEOSettings)
	var i GetSEOSettingsRow
	err := row.Scan(
		&i.Enabled,
		&i.Description,
		&i.ImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteDocument = `-- name: GetSiteDocument :one
SELECT key, enabled, content_markdown, updated_at
FROM site_documents
WHERE key = ?1
`

func (q *Queries) GetSiteDocument(ctx context.Context, key string) (SiteDocument, error) {
	row := q.db.QueryRowContext(ctx, getSiteDocument, key)
	var i SiteDocument
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.ContentMarkdown,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT language, footer_enabled, background_image_url, public_origin, steam_openid_enabled, steam_openid_proxy_port,
       browser_title, theme, a2s_refresh_seconds, a2s_jitter_seconds, a2s_retry_count, updated_at
FROM site_settings
WHERE id = 1
`

type GetSiteSettingsRow struct {
	Language             string `json:"language"`
	FooterEnabled        int64  `json:"footer_enabled"`
	BackgroundImageUrl   string `json:"background_image_url"`
	PublicOrigin         string `json:"public_origin"`
	SteamOpenidEnabled   int64  `json:"steam_openid_enabled"`
	SteamOpenidProxyPort int64  `json:"steam_openid_proxy_port"`
	BrowserTitle         string `json:"browser_title"`
	Theme                string `json:"theme"`
	A2sRefreshSeconds    int64  `json:"a2s_refresh_seconds"`
	A2sJitterSeconds     int64  `json:"a2s_jitter_seconds"`
	A2sRetryCount        int64  `json:"a2s_retry_count"`
	UpdatedAt            int64  `json:"updated_at"`
}

func (q *Queries) GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i GetSiteSettingsRow
	err := row.Scan(
		&i.Language,
		&i.FooterEnabled,
		&i.BackgroundImageUrl,
		&i.PublicOrigin,
		&i.SteamOpenidEnabled,
		&i.SteamOpenidProxyPort,
		&i.BrowserTitle,
		&i.Theme,
		&i.A2sRefreshSeconds,
		&i.A2sJitterSeconds,
		&i.A2sRetryCount,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAggregateRow = `-- name: InsertAggregateRow :exec
INSERT INTO aggregate_rows (
  kind, day, server_key, steam_id, mode, dimension, metrics_json, aggregate_version
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertAggregateRowParams struct {
	Kind             string `json:"kind"`
	Day              int64  `json:"day"`
	ServerKey        string `json:"server_key"`
	SteamID          string `json:"steam_id"`
	Mode             string `json:"mode"`
	Dimension        string `json:"dimension"`
	MetricsJson      string `json:"metrics_json"`
	AggregateVersion int64  `json:"aggregate_version"`
}

func (q *Queries) InsertAggregateRow(ctx context.Context, arg InsertAggregateRowParams) error {
	_, err := q.db.ExecContext(ctx, insertAggregateRow,
		arg.Kind,
		arg.Day,
		arg.ServerKey,
		arg.SteamID,
		arg.Mode,
		arg.Dimension,
		arg.MetricsJson,
		arg.AggregateVersion,
	)
	return err
}

const listAnnouncementYears = `-- name: ListAnnouncementYears :many
SELECT DISTINCT CAST(strftime('%Y', updated_at, 'unixepoch') AS INTEGER) AS year
FROM announcements
ORDER BY year DESC
`

func (q *Queries) ListAnnouncementYears(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncementYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var year int64
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, content_markdown, created_at, updated_at
FROM announcements
WHERE (?1 = '' OR instr(lower(title), lower(?1)) > 0)
  AND (?2 = 0 OR CAST(strftime('%Y', updated_at, 'unixepoch') AS INTEGER) = ?2)
ORDER BY created_at DESC, id DESC
LIMIT ?4 OFFSET ?3
`

type ListAnnouncementsParams struct {
	TitleFilter interface{} `json:"title_filter"`
	YearFilter  interface{} `json:"year_filter"`
	RowOffset   int64       `json:"row_offset"`
	RowLimit    int64       `json:"row_limit"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements,
		arg.TitleFilter,
		arg.YearFilter,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentMarkdown,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFooterLinks = `-- name: ListFooterLinks :many
SELECT id, label, url
FROM footer_links
ORDER BY sort_order, id
`

type ListFooterLinksRow struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	Url   string `json:"url"`
}

func (q *Queries) ListFooterLinks(ctx context.Context) ([]ListFooterLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listFooterLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFooterLinksRow{}
	for rows.Next() {
		var i ListFooterLinksRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameServers = `-- name: ListGameServers :many
SELECT
  id, display_name, address, enabled, sort_order
FROM game_servers
ORDER BY sort_order, id
`

type ListGameServersRow struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Address     string `json:"address"`
	Enabled     int64  `json:"enabled"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) ListGameServers(ctx context.Context) ([]ListGameServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGameServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameServersRow{}
	for rows.Next() {
		var i ListGameServersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Address,
			&i.Enabled,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicFooterLinks = `-- name: ListPublicFooterLinks :many
SELECT label, url
FROM footer_links
ORDER BY sort_order, id
`

type ListPublicFooterLinksRow struct {
	Label string `json:"label"`
	Url   string `json:"url"`
}

func (q *Queries) ListPublicFooterLinks(ctx context.Context) ([]ListPublicFooterLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicFooterLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFooterLinksRow{}
	for rows.Next() {
		var i ListPublicFooterLinksRow
		if err := rows.Scan(&i.Label, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSiteDocuments = `-- name: ListPublicSiteDocuments :many
SELECT key
FROM site_documents
WHERE enabled = 1 AND content_markdown <> ''
ORDER BY CASE key WHEN 'introduction' THEN 1 WHEN 'commands' THEN 2 ELSE 3 END
`

func (q *Queries) ListPublicSiteDocuments(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPublicSiteDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteDocuments = `-- name: ListSiteDocuments :many
SELECT key, enabled, content_markdown, updated_at
FROM site_documents
ORDER BY CASE key WHEN 'introduction' THEN 1 WHEN 'commands' THEN 2 ELSE 3 END
`

func (q *Queries) ListSiteDocuments(ctx context.Context) ([]SiteDocument, error) {
	rows, err := q.db.QueryContext(ctx, listSiteDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteDocument{}
	for rows.Next() {
		var i SiteDocument
		if err := rows.Scan(
			&i.Key,
			&i.Enabled,
			&i.ContentMarkdown,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAggregateFailed = `-- name: MarkAggregateFailed :exec
UPDATE aggregate_state SET state = 'failed', last_error = ?1 WHERE id = 1
`

func (q *Queries) MarkAggregateFailed(ctx context.Context, lastError string) error {
	_, err := q.db.ExecContext(ctx, markAggregateFailed, lastError)
	return err
}

const markAggregateStarted = `-- name: MarkAggregateStarted :exec
UPDATE aggregate_state SET state = 'building', last_started_at = ?1, last_error = '' WHERE id = 1
`

func (q *Queries) MarkAggregateStarted(ctx context.Context, lastStartedAt int64) error {
	_, err := q.db.ExecContext(ctx, markAggregateStarted, lastStartedAt)
	return err
}

const nextGameServerSortOrder = `-- name: NextGameServerSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM game_servers
`

func (q *Queries) NextGameServerSortOrder(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextGameServerSortOrder)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setGameServerEnabled = `-- name: SetGameServerEnabled :execrows
UPDATE game_servers SET enabled = ?2, updated_at = ?3 WHERE id = ?1
`

type SetGameServerEnabledParams struct {
	ID        string `json:"id"`
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetGameServerEnabled(ctx context.Context, arg SetGameServerEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGameServerEnabled, arg.ID, arg.Enabled, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setGameServerSortOrder = `-- name: SetGameServerSortOrder :execrows
UPDATE game_servers SET sort_order = ?2, updated_at = ?3 WHERE id = ?1
`

type SetGameServerSortOrderParams struct {
	ID        string `json:"id"`
	SortOrder int64  `json:"sort_order"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetGameServerSortOrder(ctx context.Context, arg SetGameServerSortOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGameServerSortOrder, arg.ID, arg.SortOrder, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_account SET
  password_hash = ?1,
  token_version = token_version + 1,
  updated_at = ?2,
  password_changed_at = ?2
WHERE id = 1
`

type UpdateAdminPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.UpdatedAt)
	return err
}

const updateAdminUsername = `-- name: UpdateAdminUsername :exec
UPDATE admin_account SET username = ?1, updated_at = ?2 WHERE id = 1
`

type UpdateAdminUsernameParams struct {
	Username  string `json:"username"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpdateAdminUsername(ctx context.Context, arg UpdateAdminUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUsername, arg.Username, arg.UpdatedAt)
	return err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :execrows
UPDATE announcements SET
  title = ?2,
  content_markdown = ?3,
  updated_at = ?4
WHERE id = ?1
`

type UpdateAnnouncementParams struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	ContentMarkdown string `json:"content_markdown"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAnnouncement,
		arg.ID,
		arg.Title,
		arg.ContentMarkdown,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDataMaintenanceSettings = `-- name: UpdateDataMaintenanceSettings :exec
UPDATE data_maintenance_settings SET
  aggregate_interval_minutes = ?1,
  detail_retention_days = ?2,
  session_retention_days = ?3,
  result_retention_days = ?4,
  updated_at = ?5
WHERE id = 1
`

type UpdateDataMaintenanceSettingsParams struct {
	AggregateIntervalMinutes int64 `json:"aggregate_interval_minutes"`
	DetailRetentionDays      int64 `json:"detail_retention_days"`
	SessionRetentionDays     int64 `json:"session_retention_days"`
	ResultRetentionDays      int64 `json:"result_retention_days"`
	UpdatedAt                int64 `json:"updated_at"`
}

func (q *Queries) UpdateDataMaintenanceSettings(ctx context.Context, arg UpdateDataMaintenanceSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateDataMaintenanceSettings,
		arg.AggregateIntervalMinutes,
		arg.DetailRetentionDays,
		arg.SessionRetentionDays,
		arg.ResultRetentionDays,
		arg.UpdatedAt,
	)
	return err
}

const updateGameServer = `-- name: UpdateGameServer :execrows
UPDATE game_servers SET
  display_name = ?2,
  address = ?3,
  updated_at = ?4
WHERE id = ?1
`

type UpdateGameServerParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Address     string `json:"address"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) UpdateGameServer(ctx context.Context, arg UpdateGameServerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGameServer,
		arg.ID,
		arg.DisplayName,
		arg.Address,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSiteDocument = `-- name: UpdateSiteDocument :execrows
UPDATE site_documents SET enabled = ?2, content_markdown = ?3, updated_at = ?4
WHERE key = ?1
`

type UpdateSiteDocumentParams struct {
	Key             string `json:"key"`
	Enabled         int64  `json:"enabled"`
	ContentMarkdown string `json:"content_markdown"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpdateSiteDocument(ctx context.Context, arg UpdateSiteDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSiteDocument,
		arg.Key,
		arg.Enabled,
		arg.ContentMarkdown,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMetadata = `-- name: UpsertMetadata :exec
INSERT INTO dashboard_metadata (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadata, arg.Key, arg.Value)
	return err
}

const upsertSEOSettings = `-- name: UpsertSEOSettings :exec
INSERT INTO site_seo_settings (id, enabled, description, image_url, updated_at)
VALUES (1, ?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET
  enabled = excluded.enabled,
  description = excluded.description,
  image_url = excluded.image_url,
  updated_at = excluded.updated_at
`

type UpsertSEOSettingsParams struct {
	Enabled     int64  `json:"enabled"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) UpsertSEOSettings(ctx context.Context, arg UpsertSEOSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSEOSettings,
		arg.Enabled,
		arg.Description,
		arg.ImageUrl,
		arg.UpdatedAt,
	)
	return err
}

const upsertSiteSettings = `-- name: UpsertSiteSettings :exec
INSERT INTO site_settings (
  id, language, footer_enabled, background_image_url, public_origin, steam_openid_enabled, steam_openid_proxy_port,
  browser_title, theme, a2s_refresh_seconds, a2s_jitter_seconds, a2s_retry_count, updated_at
)
VALUES (1, ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
ON CONFLICT(id) DO UPDATE SET
  language = excluded.language,
  footer_enabled = excluded.footer_enabled,
  background_image_url = excluded.background_image_url,
  public_origin = excluded.public_origin,
  steam_openid_enabled = excluded.steam_openid_enabled,
  steam_openid_proxy_port = excluded.steam_openid_proxy_port,
  browser_title = excluded.browser_title,
  theme = excluded.theme,
  a2s_refresh_seconds = excluded.a2s_refresh_seconds,
  a2s_jitter_seconds = excluded.a2s_jitter_seconds,
  a2s_retry_count = excluded.a2s_retry_count,
  updated_at = excluded.updated_at
`

type UpsertSiteSettingsParams struct {
	Language             string `json:"language"`
	FooterEnabled        int64  `json:"footer_enabled"`
	BackgroundImageUrl   string `json:"background_image_url"`
	PublicOrigin         string `json:"public_origin"`
	SteamOpenidEnabled   int64  `json:"steam_openid_enabled"`
	SteamOpenidProxyPort int64  `json:"steam_openid_proxy_port"`
	BrowserTitle         string `json:"browser_title"`
	Theme                string `json:"theme"`
	A2sRefreshSeconds    int64  `json:"a2s_refresh_seconds"`
	A2sJitterSeconds     int64  `json:"a2s_jitter_seconds"`
	A2sRetryCount        int64  `json:"a2s_retry_count"`
	UpdatedAt            int64  `json:"updated_at"`
}

func (q *Queries) UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteSettings,
		arg.Language,
		arg.FooterEnabled,
		arg.BackgroundImageUrl,
		arg.PublicOrigin,
		arg.SteamOpenidEnabled,
		arg.SteamOpenidProxyPort,
		arg.BrowserTitle,
		arg.Theme,
		arg.A2sRefreshSeconds,
		arg.A2sJitterSeconds,
		arg.A2sRetryCount,
		arg.UpdatedAt,
	)
	return err
}
