// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dashsql

import (
	"context"
)

const countGameServers = `-- name: CountGameServers :one
SELECT COUNT(*) FROM game_servers
`

func (q *Queries) CountGameServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGameServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteSettings = `-- name: CountSiteSettings :one
SELECT COUNT(*) FROM site_settings
`

func (q *Queries) CountSiteSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSiteSettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFooterLink = `-- name: CreateFooterLink :exec
INSERT INTO footer_links (
  label, url, sort_order, open_new_tab, enabled, created_at, updated_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type CreateFooterLinkParams struct {
	Label      string `json:"label"`
	Url        string `json:"url"`
	SortOrder  int64  `json:"sort_order"`
	OpenNewTab int64  `json:"open_new_tab"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateFooterLink(ctx context.Context, arg CreateFooterLinkParams) error {
	_, err := q.db.ExecContext(ctx, createFooterLink,
		arg.Label,
		arg.Url,
		arg.SortOrder,
		arg.OpenNewTab,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createGameServer = `-- name: CreateGameServer :exec
INSERT INTO game_servers (
  server_key, display_name, connect_address, query_address,
  is_primary, enabled, sort_order, created_at, updated_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type CreateGameServerParams struct {
	ServerKey      string `json:"server_key"`
	DisplayName    string `json:"display_name"`
	ConnectAddress string `json:"connect_address"`
	QueryAddress   string `json:"query_address"`
	IsPrimary      int64  `json:"is_primary"`
	Enabled        int64  `json:"enabled"`
	SortOrder      int64  `json:"sort_order"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateGameServer(ctx context.Context, arg CreateGameServerParams) error {
	_, err := q.db.ExecContext(ctx, createGameServer,
		arg.ServerKey,
		arg.DisplayName,
		arg.ConnectAddress,
		arg.QueryAddress,
		arg.IsPrimary,
		arg.Enabled,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFooterLinks = `-- name: DeleteFooterLinks :exec
DELETE FROM footer_links
`

func (q *Queries) DeleteFooterLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFooterLinks)
	return err
}

const deleteGameServers = `-- name: DeleteGameServers :exec
DELETE FROM game_servers
`

func (q *Queries) DeleteGameServers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGameServers)
	return err
}

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM dashboard_metadata WHERE key = ?1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getPrimaryServer = `-- name: GetPrimaryServer :one
SELECT
  id, server_key, display_name, connect_address, query_address,
  is_primary, enabled, sort_order
FROM game_servers
WHERE is_primary = 1 AND enabled = 1
LIMIT 1
`

type GetPrimaryServerRow struct {
	ID             int64  `json:"id"`
	ServerKey      string `json:"server_key"`
	DisplayName    string `json:"display_name"`
	ConnectAddress string `json:"connect_address"`
	QueryAddress   string `json:"query_address"`
	IsPrimary      int64  `json:"is_primary"`
	Enabled        int64  `json:"enabled"`
	SortOrder      int64  `json:"sort_order"`
}

func (q *Queries) GetPrimaryServer(ctx context.Context) (GetPrimaryServerRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryServer)
	var i GetPrimaryServerRow
	err := row.Scan(
		&i.ID,
		&i.ServerKey,
		&i.DisplayName,
		&i.ConnectAddress,
		&i.QueryAddress,
		&i.IsPrimary,
		&i.Enabled,
		&i.SortOrder,
	)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT title, footer_text, updated_at
FROM site_settings
WHERE id = 1
`

type GetSiteSettingsRow struct {
	Title      string `json:"title"`
	FooterText string `json:"footer_text"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i GetSiteSettingsRow
	err := row.Scan(&i.Title, &i.FooterText, &i.UpdatedAt)
	return i, err
}

const listEnabledFooterLinks = `-- name: ListEnabledFooterLinks :many
SELECT label, url, open_new_tab
FROM footer_links
WHERE enabled = 1
ORDER BY sort_order, id
`

type ListEnabledFooterLinksRow struct {
	Label      string `json:"label"`
	Url        string `json:"url"`
	OpenNewTab int64  `json:"open_new_tab"`
}

func (q *Queries) ListEnabledFooterLinks(ctx context.Context) ([]ListEnabledFooterLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledFooterLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledFooterLinksRow{}
	for rows.Next() {
		var i ListEnabledFooterLinksRow
		if err := rows.Scan(&i.Label, &i.Url, &i.OpenNewTab); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetadata = `-- name: UpsertMetadata :exec
INSERT INTO dashboard_metadata (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadata, arg.Key, arg.Value)
	return err
}

const upsertSiteSettings = `-- name: UpsertSiteSettings :exec
INSERT INTO site_settings (id, title, footer_text, updated_at)
VALUES (1, ?1, ?2, ?3)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  footer_text = excluded.footer_text,
  updated_at = excluded.updated_at
`

type UpsertSiteSettingsParams struct {
	Title      string `json:"title"`
	FooterText string `json:"footer_text"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteSettings, arg.Title, arg.FooterText, arg.UpdatedAt)
	return err
}
