// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dashsql

type DashboardMetadatum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type FooterLink struct {
	ID         int64  `json:"id"`
	Label      string `json:"label"`
	Url        string `json:"url"`
	SortOrder  int64  `json:"sort_order"`
	OpenNewTab int64  `json:"open_new_tab"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type GameServer struct {
	ID             int64  `json:"id"`
	ServerKey      string `json:"server_key"`
	DisplayName    string `json:"display_name"`
	ConnectAddress string `json:"connect_address"`
	QueryAddress   string `json:"query_address"`
	IsPrimary      int64  `json:"is_primary"`
	Enabled        int64  `json:"enabled"`
	SortOrder      int64  `json:"sort_order"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type SiteSetting struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	FooterText string `json:"footer_text"`
	UpdatedAt  int64  `json:"updated_at"`
}
