// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dashsql

import (
	"context"
)

type Querier interface {
	CountGameServers(ctx context.Context) (int64, error)
	CountSiteSettings(ctx context.Context) (int64, error)
	CreateFooterLink(ctx context.Context, arg CreateFooterLinkParams) error
	CreateGameServer(ctx context.Context, arg CreateGameServerParams) error
	DeleteFooterLinks(ctx context.Context) error
	DeleteGameServers(ctx context.Context) error
	GetMetadata(ctx context.Context, key string) (string, error)
	GetPrimaryServer(ctx context.Context) (GetPrimaryServerRow, error)
	GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error)
	ListEnabledFooterLinks(ctx context.Context) ([]ListEnabledFooterLinksRow, error)
	UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error
	UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) error
}

var _ Querier = (*Queries)(nil)
