// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package statsmysql

import (
	"context"
	"database/sql"
)

const getPlayerPVE = `-- name: GetPlayerPVE :one
SELECT
  CAST(COALESCE(SUM(p.common_kills),0) AS SIGNED) common_kills,
  CAST(COALESCE(SUM(p.special_kills),0) AS SIGNED) special_kills,
  CAST(COALESCE(SUM(p.tank_kills),0) AS SIGNED) tank_kills,
  CAST(COALESCE(SUM(p.witch_kills),0) AS SIGNED) witch_kills,
  CAST(COALESCE(SUM(p.damage_to_special),0) AS SIGNED) damage_to_special,
  CAST(COALESCE(SUM(p.damage_to_tank),0) AS SIGNED) damage_to_tank,
  CAST(COALESCE(SUM(p.damage_to_witch),0) AS SIGNED) damage_to_witch,
  CAST(COALESCE(SUM(p.damage_taken_infected),0) AS SIGNED) damage_taken,
  CAST(COALESCE(SUM(p.friendly_fire_to_humans+p.friendly_fire_to_bots),0) AS SIGNED) friendly_fire,
  CAST(COALESCE(SUM(p.incapacitations),0) AS SIGNED) incapacitations,
  CAST(COALESCE(SUM(p.deaths),0) AS SIGNED) deaths,
  CAST(COALESCE(SUM(p.incap_revives+p.ledge_rescues+p.defib_revives),0) AS SIGNED) revives,
  CAST(COALESCE(SUM(p.rescues_received),0) AS SIGNED) rescues_received,
  CAST(COALESCE(SUM(p.medkits_used_self+p.medkits_used_on_others),0) AS SIGNED) medkits_used,
  CAST(COALESCE(SUM(p.medkit_healing_self+p.medkit_healing_others),0) AS SIGNED) healing,
  CAST(COALESCE(SUM(p.chapter_participations),0) AS SIGNED) chapter_participations,
  CAST(COALESCE(SUM(p.chapter_completions_alive+p.chapter_completions_dead),0) AS SIGNED) chapter_completions,
  CAST(COALESCE(SUM(p.campaign_completions),0) AS SIGNED) campaign_completions
FROM lps_pve_segment_stats p
JOIN lps_player_segments s ON s.segment_id=p.segment_id
JOIN lps_runs r ON r.run_id=s.run_id
WHERE s.steam_id=? AND s.side='survivor' AND p.stats_version=1
  AND r.mode_family='pve' AND r.game_mode IN ('coop','realism')
  AND (?=0 OR s.started_at>=?)
`

type GetPlayerPVEParams struct {
	SteamID string
	Cutoff  int64
}

type GetPlayerPVERow struct {
	CommonKills           int64
	SpecialKills          int64
	TankKills             int64
	WitchKills            int64
	DamageToSpecial       int64
	DamageToTank          int64
	DamageToWitch         int64
	DamageTaken           int64
	FriendlyFire          int64
	Incapacitations       int64
	Deaths                int64
	Revives               int64
	RescuesReceived       int64
	MedkitsUsed           int64
	Healing               int64
	ChapterParticipations int64
	ChapterCompletions    int64
	CampaignCompletions   int64
}

func (q *Queries) GetPlayerPVE(ctx context.Context, arg GetPlayerPVEParams) (GetPlayerPVERow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerPVE, arg.SteamID, arg.Cutoff, arg.Cutoff)
	var i GetPlayerPVERow
	err := row.Scan(
		&i.CommonKills,
		&i.SpecialKills,
		&i.TankKills,
		&i.WitchKills,
		&i.DamageToSpecial,
		&i.DamageToTank,
		&i.DamageToWitch,
		&i.DamageTaken,
		&i.FriendlyFire,
		&i.Incapacitations,
		&i.Deaths,
		&i.Revives,
		&i.RescuesReceived,
		&i.MedkitsUsed,
		&i.Healing,
		&i.ChapterParticipations,
		&i.ChapterCompletions,
		&i.CampaignCompletions,
	)
	return i, err
}

const getPlayerSummary = `-- name: GetPlayerSummary :one
SELECT p.steam_id, p.last_name, p.first_seen_at, p.last_seen_at,
  CAST((SELECT COUNT(*) FROM lps_sessions s WHERE s.steam_id=p.steam_id) AS SIGNED) AS session_count,
  CAST((SELECT COALESCE(SUM(s.connected_seconds),0) FROM lps_sessions s WHERE s.steam_id=p.steam_id) AS SIGNED) AS connected_seconds,
  CAST((SELECT COALESCE(SUM(s.active_play_seconds),0) FROM lps_sessions s WHERE s.steam_id=p.steam_id) AS SIGNED) AS active_play_seconds
FROM lps_players p WHERE p.steam_id=?
`

type GetPlayerSummaryRow struct {
	SteamID           string
	LastName          string
	FirstSeenAt       int64
	LastSeenAt        int64
	SessionCount      int64
	ConnectedSeconds  int64
	ActivePlaySeconds int64
}

func (q *Queries) GetPlayerSummary(ctx context.Context, steamID string) (GetPlayerSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerSummary, steamID)
	var i GetPlayerSummaryRow
	err := row.Scan(
		&i.SteamID,
		&i.LastName,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.SessionCount,
		&i.ConnectedSeconds,
		&i.ActivePlaySeconds,
	)
	return i, err
}

const getPlayerVersus = `-- name: GetPlayerVersus :one
WITH survivor AS (
  SELECT
    CAST(COALESCE(SUM(v.common_kills),0) AS SIGNED) common_kills,
    CAST(COALESCE(SUM(v.human_special_kills),0) AS SIGNED) human_special_kills,
    CAST(COALESCE(SUM(v.bot_special_kills),0) AS SIGNED) bot_special_kills,
    CAST(COALESCE(SUM(v.human_tank_kills),0) AS SIGNED) human_tank_kills,
    CAST(COALESCE(SUM(v.bot_tank_kills),0) AS SIGNED) bot_tank_kills,
    CAST(COALESCE(SUM(v.damage_to_human_special+v.damage_to_bot_special+v.damage_to_human_tank+v.damage_to_bot_tank),0) AS SIGNED) survivor_damage,
    CAST(COALESCE(SUM(v.deaths),0) AS SIGNED) survivor_deaths,
    CAST(COALESCE(SUM(v.incap_revives+v.ledge_rescues+v.defib_revives),0) AS SIGNED) survivor_revives
  FROM lps_versus_survivor_stats v
  JOIN lps_player_segments s ON s.segment_id=v.segment_id JOIN lps_runs r ON r.run_id=s.run_id
  WHERE s.steam_id=? AND s.side='survivor' AND v.stats_version=1
    AND r.mode_family='versus' AND r.game_mode='versus' AND (?=0 OR s.started_at>=?)
), infected AS (
  SELECT CAST(COALESCE(SUM(v.spawn_count),0) AS SIGNED) infected_spawns,
    CAST(COALESCE(SUM(v.damage_to_human_survivors),0) AS SIGNED) damage_to_human_survivors,
    CAST(COALESCE(SUM(v.human_survivor_incaps),0) AS SIGNED) human_survivor_incaps,
    CAST(COALESCE(SUM(v.human_survivor_kills),0) AS SIGNED) human_survivor_kills
  FROM lps_versus_infected_stats v
  JOIN lps_player_segments s ON s.segment_id=v.segment_id JOIN lps_runs r ON r.run_id=s.run_id
  WHERE s.steam_id=? AND s.side='infected' AND v.stats_version=1
    AND r.mode_family='versus' AND r.game_mode='versus' AND (?=0 OR s.started_at>=?)
), controls AS (
  SELECT CAST(COALESCE(SUM(c.human_survivor_controls),0) AS SIGNED) human_survivor_controls,
    CAST(COALESCE(SUM(c.human_survivor_control_seconds),0) AS SIGNED) human_survivor_control_seconds
  FROM lps_versus_infected_class_stats c
  JOIN lps_player_segments s ON s.segment_id=c.segment_id JOIN lps_runs r ON r.run_id=s.run_id
  WHERE s.steam_id=? AND s.side='infected' AND c.stats_version=1
    AND r.mode_family='versus' AND r.game_mode='versus' AND (?=0 OR s.started_at>=?)
)
SELECT survivor.common_kills, survivor.human_special_kills, survivor.bot_special_kills, survivor.human_tank_kills, survivor.bot_tank_kills, survivor.survivor_damage, survivor.survivor_deaths, survivor.survivor_revives, infected.infected_spawns, infected.damage_to_human_survivors, infected.human_survivor_incaps, infected.human_survivor_kills, controls.human_survivor_controls, controls.human_survivor_control_seconds FROM survivor CROSS JOIN infected CROSS JOIN controls
`

type GetPlayerVersusParams struct {
	SteamID string
	Cutoff  int64
}

type GetPlayerVersusRow struct {
	CommonKills                 int64
	HumanSpecialKills           int64
	BotSpecialKills             int64
	HumanTankKills              int64
	BotTankKills                int64
	SurvivorDamage              int64
	SurvivorDeaths              int64
	SurvivorRevives             int64
	InfectedSpawns              int64
	DamageToHumanSurvivors      int64
	HumanSurvivorIncaps         int64
	HumanSurvivorKills          int64
	HumanSurvivorControls       int64
	HumanSurvivorControlSeconds int64
}

func (q *Queries) GetPlayerVersus(ctx context.Context, arg GetPlayerVersusParams) (GetPlayerVersusRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerVersus,
		arg.SteamID,
		arg.Cutoff,
		arg.Cutoff,
		arg.SteamID,
		arg.Cutoff,
		arg.Cutoff,
		arg.SteamID,
		arg.Cutoff,
		arg.Cutoff,
	)
	var i GetPlayerVersusRow
	err := row.Scan(
		&i.CommonKills,
		&i.HumanSpecialKills,
		&i.BotSpecialKills,
		&i.HumanTankKills,
		&i.BotTankKills,
		&i.SurvivorDamage,
		&i.SurvivorDeaths,
		&i.SurvivorRevives,
		&i.InfectedSpawns,
		&i.DamageToHumanSurvivors,
		&i.HumanSurvivorIncaps,
		&i.HumanSurvivorKills,
		&i.HumanSurvivorControls,
		&i.HumanSurvivorControlSeconds,
	)
	return i, err
}

const listPlayerChapters = `-- name: ListPlayerChapters :many
SELECT s.segment_id,s.server_key,r.mode_family,r.game_mode,rd.map_name,s.side,s.started_at,s.ended_at,s.active_play_seconds,s.status
FROM lps_player_segments s JOIN lps_runs r ON r.run_id=s.run_id JOIN lps_rounds rd ON rd.round_id=s.round_id
WHERE s.steam_id=?
  AND (?=0 OR s.started_at<?
    OR (s.started_at=? AND s.segment_id<?))
ORDER BY s.started_at DESC,s.segment_id DESC LIMIT ?
`

type ListPlayerChaptersParams struct {
	SteamID         string
	CursorStartedAt int64
	CursorID        string
	Limit           int32
}

type ListPlayerChaptersRow struct {
	SegmentID         string
	ServerKey         string
	ModeFamily        string
	GameMode          string
	MapName           string
	Side              string
	StartedAt         int64
	EndedAt           sql.NullInt64
	ActivePlaySeconds int64
	Status            string
}

func (q *Queries) ListPlayerChapters(ctx context.Context, arg ListPlayerChaptersParams) ([]ListPlayerChaptersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerChapters,
		arg.SteamID,
		arg.CursorStartedAt,
		arg.CursorStartedAt,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerChaptersRow{}
	for rows.Next() {
		var i ListPlayerChaptersRow
		if err := rows.Scan(
			&i.SegmentID,
			&i.ServerKey,
			&i.ModeFamily,
			&i.GameMode,
			&i.MapName,
			&i.Side,
			&i.StartedAt,
			&i.EndedAt,
			&i.ActivePlaySeconds,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerSessions = `-- name: ListPlayerSessions :many
SELECT session_id,server_key,player_name,started_at,ended_at,connected_seconds,active_play_seconds,status,disconnect_reason
FROM lps_sessions WHERE steam_id=?
  AND (?=0 OR started_at<?
    OR (started_at=? AND session_id<?))
ORDER BY started_at DESC,session_id DESC LIMIT ?
`

type ListPlayerSessionsParams struct {
	SteamID         string
	CursorStartedAt int64
	CursorID        string
	Limit           int32
}

type ListPlayerSessionsRow struct {
	SessionID         string
	ServerKey         string
	PlayerName        string
	StartedAt         int64
	EndedAt           sql.NullInt64
	ConnectedSeconds  int64
	ActivePlaySeconds int64
	Status            string
	DisconnectReason  string
}

func (q *Queries) ListPlayerSessions(ctx context.Context, arg ListPlayerSessionsParams) ([]ListPlayerSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerSessions,
		arg.SteamID,
		arg.CursorStartedAt,
		arg.CursorStartedAt,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerSessionsRow{}
	for rows.Next() {
		var i ListPlayerSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ServerKey,
			&i.PlayerName,
			&i.StartedAt,
			&i.EndedAt,
			&i.ConnectedSeconds,
			&i.ActivePlaySeconds,
			&i.Status,
			&i.DisconnectReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT steam_id, last_name
FROM lps_players
WHERE CAST(? AS CHAR) = ''
   OR LOWER(last_name) LIKE CONCAT('%', LOWER(CAST(? AS CHAR)), '%')
   OR steam_id LIKE CONCAT('%', CAST(? AS CHAR), '%')
ORDER BY last_seen_at DESC, steam_id ASC
LIMIT ?
`

type SearchPlayersParams struct {
	SearchQuery interface{}
	Limit       int32
}

type SearchPlayersRow struct {
	SteamID  string
	LastName string
}

func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlayers,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(&i.SteamID, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
