// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package statsmysql

import (
	"context"
)

type Querier interface {
	GetCoreOverview(ctx context.Context, lastSavedAt int64) (GetCoreOverviewRow, error)
	GetPVEOverview(ctx context.Context) (GetPVEOverviewRow, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	GetVersusOverview(ctx context.Context) (GetVersusOverviewRow, error)
}

var _ Querier = (*Queries)(nil)
